field: c5ad5d5e-653f-4b32-ac93-039578cbb009
fieldLayouts:
  8bd66942-e37a-4af9-b1e0-d9338c6f09cb:
    tabs:
      -
        elements:
          -
            fieldUid: 2e095ecc-72ae-421c-bbaa-4c9f4bb55f30
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  2e095ecc-72ae-421c-bbaa-4c9f4bb55f30:
    contentColumnType: string
    fieldGroup: null
    handle: grandeimage
    instructions: ''
    name: grandeImage
    searchable: true
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:eff0dab7-b33f-4b25-bd91-d98f373e8131'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:eff0dab7-b33f-4b25-bd91-d98f373e8131'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: true
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: grandeImage
name: 'Grande Image'
sortOrder: 5
