field: faf0f324-c747-46f4-bc01-c4eca141da00
fieldLayouts:
  8fdc1fbd-a2d6-46ca-86b9-728c717cd94c:
    tabs:
      -
        fields:
          3d62d479-d3a3-425d-bb20-354acc52633e:
            required: false
            sortOrder: 1
        name: Content
        sortOrder: 1
fields:
  3d62d479-d3a3-425d-bb20-354acc52633e:
    contentColumnType: string
    fieldGroup: null
    handle: imageGalleryItem
    instructions: ''
    name: Image
    searchable: true
    settings:
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:eff0dab7-b33f-4b25-bd91-d98f373e8131'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: '1'
      restrictFiles: '1'
      selectionLabel: 'Ajouter une image'
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:eff0dab7-b33f-4b25-bd91-d98f373e8131'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: 84b6bb21-bdc2-41fb-b07a-7c343f7a7288
      useSingleFolder: false
      validateRelatedElements: '1'
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: imageGallery
name: Image
sortOrder: 1
