field: c5ad5d5e-653f-4b32-ac93-039578cbb009
fieldLayouts:
  4dfbd996-a2f6-4454-8250-91a80c4ff2f3:
    tabs:
      -
        elements:
          -
            fieldUid: 1a1303e4-39c9-4e40-a7c8-e52a9cd0bb88
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: eb588270-9789-47a8-bb85-6cc524d510df
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: bca2ed0f-b69a-4f6e-ab9a-e7f7bf8a515d
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 084f6562-7592-4b20-b133-4f643016ce60
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  084f6562-7592-4b20-b133-4f643016ce60:
    contentColumnType: string(255)
    fieldGroup: null
    handle: lienDuBouton
    instructions: ''
    name: 'Lien du bouton'
    searchable: true
    settings:
      maxLength: '255'
      placeholder: ''
    translationKeyFormat: null
    translationMethod: language
    type: craft\fields\Url
  1a1303e4-39c9-4e40-a7c8-e52a9cd0bb88:
    contentColumnType: text
    fieldGroup: null
    handle: titreTexteCentre
    instructions: ''
    name: Titre
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: language
    type: craft\fields\PlainText
  bca2ed0f-b69a-4f6e-ab9a-e7f7bf8a515d:
    contentColumnType: text
    fieldGroup: null
    handle: texteDuBoutonTexteCentre
    instructions: ''
    name: 'Texte du bouton'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: 'En savoir plus'
      uiMode: normal
    translationKeyFormat: null
    translationMethod: language
    type: craft\fields\PlainText
  eb588270-9789-47a8-bb85-6cc524d510df:
    contentColumnType: text
    fieldGroup: null
    handle: texteTexteCentre
    instructions: ''
    name: Texte
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: language
    type: craft\redactor\Field
handle: texteCentre
name: 'Texte centré'
sortOrder: 1
