fieldLayouts:
  910b25bf-1dbb-466e-8cec-eae5a51328a3:
    tabs:
      -
        elements:
          -
            instructions: null
            label: ''
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 7ad4ebb2-6984-4493-af9b-711e316d719f
            required: true
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 06fdaf69-6885-4f95-9c1f-aa85e44c2751
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 805830ad-0fe4-4b9d-8a8e-cbe831914644
            required: true
            type: craft\fieldlayoutelements\CustomField
        name: Hero
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 0f3d0dc1-5cfc-47c8-bd27-6cceb12e282a
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: d99d660a-b341-4c74-baee-e6a021d49b26
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: a6e395ea-6105-4494-8cae-027268f59213
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 775006d6-7318-43d0-8861-80559b0f28f5
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Introduction
        sortOrder: 2
      -
        elements:
          -
            fieldUid: c5ad5d5e-653f-4b32-ac93-039578cbb009
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Contenu
        sortOrder: 3
      -
        elements:
          -
            fieldUid: bb2c1b72-b68d-4e9b-9996-bdd484d6074f
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: 'Liens vers page'
        sortOrder: 4
handle: accueil
hasTitleField: false
name: Accueil
section: 5babcc08-e86b-49bd-977e-fddfdc2297f8
sortOrder: 1
titleFormat: '{section.name|raw}'
