fieldLayouts:
  dcbea026-2245-4202-93eb-88bc446f7eb5:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: Titre
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: f7e4b87b-a0f1-4605-96d3-07a55640216f
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 1ad1fa2f-ff3d-4da5-8b01-d07110082775
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Général
        sortOrder: 1
      -
        elements:
          -
            fieldUid: c5ad5d5e-653f-4b32-ac93-039578cbb009
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Contenu
        sortOrder: 2
      -
        elements:
          -
            fieldUid: faf0f324-c747-46f4-bc01-c4eca141da00
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Galerie photos'
        sortOrder: 3
handle: b2b
hasTitleField: true
name: B2B
section: 3876e609-694d-4eb0-9d5d-07053610b3ce
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: ''
