fieldLayouts:
  a2c14d6e-937f-4205-8a90-8a9004faa6e6:
    tabs:
      -
        elements:
          -
            instructions: null
            label: ''
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 7ad4ebb2-6984-4493-af9b-711e316d719f
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: 'Tab 1'
        sortOrder: 1
handle: blog
hasTitleField: false
name: Blog
section: cfb01997-c7b1-4719-9842-1e9e8890b2d4
sortOrder: 1
titleFormat: '{section.name|raw}'
