fieldLayouts:
  cb2d7bb6-444c-44f9-a67d-5312bcd86a15:
    tabs:
      -
        elements:
          -
            instructions: null
            label: ''
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 7ad4ebb2-6984-4493-af9b-711e316d719f
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: 'Tab 1'
        sortOrder: 1
handle: devis
hasTitleField: false
name: Devis
section: cd283052-4ad6-4468-9df9-0cfb897c3d46
sortOrder: 1
titleFormat: '{section.name|raw}'
