fieldLayouts:
  c5659644-9c3f-458f-9a30-773171689829:
    tabs:
      -
        elements:
          -
            instructions: null
            label: Titre
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 90e10643-7f18-492b-9868-6f8f394f8697
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 805830ad-0fe4-4b9d-8a8e-cbe831914644
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 7299febf-bd65-46b0-bf6e-d3982f880e4a
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 1130af81-e837-4798-963e-29d1894bc3e9
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 7ce748c8-a445-475a-9687-77c4e2f32e81
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: f7e4b87b-a0f1-4605-96d3-07a55640216f
            required: true
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 1ad1fa2f-ff3d-4da5-8b01-d07110082775
            required: true
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 67c76d67-ce8d-4f9c-81a1-9b480f2bfea0
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Général
        sortOrder: 1
      -
        elements:
          -
            fieldUid: c5ad5d5e-653f-4b32-ac93-039578cbb009
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Contenu
        sortOrder: 2
      -
        elements:
          -
            fieldUid: c591a305-97e2-4d5c-b0b8-171fbbcbe90f
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Packs
        sortOrder: 3
      -
        elements:
          -
            fieldUid: 35a7d6bb-02e9-412e-b312-b89ba1174da7
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Activités
        sortOrder: 4
      -
        elements:
          -
            fieldUid: d346fba9-40ab-4fea-9f29-b166b5a64471
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 4f0111f1-68c4-4445-a2c9-99aec438b65c
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 538e553a-832b-4fdf-8bdd-df079ea85c46
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 48ded399-33ff-4fa5-84b3-eb75c8d8d54b
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Maps
        sortOrder: 5
handle: monde
hasTitleField: true
name: Monde
section: aaa28725-19e7-408f-9a9d-a8bbfe69233f
sortOrder: 1
titleFormat: ''
