fieldLayouts:
  fc108e18-817f-426f-8648-ec8bf18f0071:
    tabs:
      -
        fields:
          f7e4b87b-a0f1-4605-96d3-07a55640216f:
            required: false
            sortOrder: 1
        name: 'Tab 1'
        sortOrder: 1
handle: activity
name: Activité
siteSettings:
  3e688797-0718-4e03-a06c-6c0acf236e7b:
    hasUrls: true
    template: ''
    uriFormat: 'activiteit/{slug}'
  84b6bb21-bdc2-41fb-b07a-7c343f7a7288:
    hasUrls: true
    template: ''
    uriFormat: 'activité/{slug}'
  de5f043b-b6bd-4feb-89c2-c5e38cef6faf:
    hasUrls: true
    template: ''
    uriFormat: 'activité/{slug}'
structure:
  maxLevels: null
  uid: 2a433daa-e6bb-4183-ae84-82b9706ef4d8
