fieldLayouts:
  fc108e18-817f-426f-8648-ec8bf18f0071:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
          -
            fieldUid: f7e4b87b-a0f1-4605-96d3-07a55640216f
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Tab 1'
        sortOrder: 1
handle: activity
name: Activité
siteSettings:
  3e688797-0718-4e03-a06c-6c0acf236e7b:
    hasUrls: true
    template: null
    uriFormat: 'activiteit/{slug}'
  84b6bb21-bdc2-41fb-b07a-7c343f7a7288:
    hasUrls: true
    template: null
    uriFormat: 'activité/{slug}'
  de5f043b-b6bd-4feb-89c2-c5e38cef6faf:
    hasUrls: true
    template: null
    uriFormat: 'activité/{slug}'
structure:
  maxLevels: null
  uid: 2a433daa-e6bb-4183-ae84-82b9706ef4d8
