contentColumnType: string
fieldGroup: 81d0e628-aea8-479b-a95f-077bc7d85acc
handle: blocs
instructions: ''
name: Blocs
searchable: true
settings:
  contentTable: '{{%matrixcontent_blocs}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: language
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
