contentColumnType: string
fieldGroup: 94636160-e0db-4242-a71e-c1080db25792
handle: imageNews
instructions: ''
name: 'Image Principale'
searchable: true
settings:
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:eff0dab7-b33f-4b25-bd91-d98f373e8131'
  defaultUploadLocationSubpath: ''
  limit: ''
  localizeRelations: ''
  restrictFiles: '1'
  selectionLabel: ''
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:eff0dab7-b33f-4b25-bd91-d98f373e8131'
  singleUploadLocationSubpath: ''
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: true
  validateRelatedElements: ''
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
