contentColumnType: string
fieldGroup: 81d0e628-aea8-479b-a95f-077bc7d85acc
handle: pack
instructions: 'Lier des packs à cette page'
name: Pack
searchable: true
settings:
  limit: ''
  localizeRelations: '1'
  selectionLabel: 'Ajouter un pack'
  source: null
  sources:
    - 'section:2abc0dfb-ffe2-488d-bab3-780b03da640c'
  targetSiteId: null
  validateRelatedElements: '1'
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
