contentColumnType: text
fieldGroup: b7be47d6-258f-4559-be92-1cba6a6ca448
handle: textIntro
instructions: ''
name: 'Texte Intro'
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  cleanupHtml: true
  columnType: text
  purifierConfig: ''
  purifyHtml: '1'
  redactorConfig: ''
  removeEmptyTags: '1'
  removeInlineStyles: '1'
  removeNbsp: '1'
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
translationKeyFormat: null
translationMethod: language
type: craft\redactor\Field
