dateModified: 1612429221
email:
  fromEmail: douffetphilippe@gmail.com
  fromName: 'La Petite Merveille'
  transportType: craft\mail\transportadapters\Sendmail
plugins:
  admin-bar:
    edition: standard
    enabled: true
    schemaVersion: 3.1.0
    settings:
      customCss: ''
      customLinks:
        -
          __assoc__:
            -
              - linkLabel
              - ''
            -
              - linkUrl
              - ''
            -
              - adminOnly
              - ''
      displayDashboardLink: true
      displayDefaultEditSection: true
      displayEditAuthor: true
      displayEditDate: true
      displayGreeting: true
      displayGuideLink: true
      displayLogout: true
      displayRevisionNote: true
      displaySettingsLink: true
      enableMobileMenu: true
      widgets:
        __assoc__:
          -
            - admin-bar_edit-links
            - '1'
  contact-form:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      allowAttachments: ''
      prependSender: 'De la part de'
      prependSubject: 'New message from Site FR (principal)'
      successFlashMessage: 'Votre message a été envoyé.'
      toEmail: dev@webdigitales.be
  contact-form-honeypot:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  image-optimize:
    edition: standard
    enabled: true
    licenseKey: 4DGTX9F2QGNPDP3PVYDMN84N
    schemaVersion: 1.0.0
    settings:
      allowUpScaledImageVariants: false
      assetVolumeSubFolders: true
      autoSharpenScaledImages: true
      createColorPalette: true
      createPlaceholderSilhouettes: false
      imageTransformTypeSettings:
        __assoc__:
          -
            - nystudio107\imageoptimizeimgix\imagetransforms\ImgixImageTransform
            -
              __assoc__:
                -
                  - domain
                  - ''
                -
                  - apiKey
                  - ''
                -
                  - securityToken
                  - ''
          -
            - nystudio107\imageoptimizesharp\imagetransforms\SharpImageTransform
            -
              __assoc__:
                -
                  - baseUrl
                  - ''
          -
            - nystudio107\imageoptimizethumbor\imagetransforms\ThumborImageTransform
            -
              __assoc__:
                -
                  - baseUrl
                  - ''
                -
                  - securityKey
                  - ''
      lowerQualityRetinaImageVariants: true
      transformClass: nystudio107\imageoptimize\imagetransforms\CraftImageTransform
  link:
    edition: standard
    enabled: true
    licenseKey: 8HCYW82Y94SN86LN1NJNKDW4
    schemaVersion: 2.0.0
  navigation:
    edition: standard
    enabled: true
    licenseKey: A3PSWAW0FFRVPC377CENQ4TE
    schemaVersion: 1.0.21
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  seomatic:
    edition: standard
    enabled: true
    licenseKey: 4K8S679HU3MIGTZXM5HZ12SC
    schemaVersion: 3.0.9
    settings:
      addHrefLang: true
      addPaginatedHreflang: true
      addXDefaultHrefLang: true
      cpTitlePrefix: '⚙ '
      devModeCpTitlePrefix: '&#x1f6a7;⚙ '
      devModeTitlePrefix: ''
      displayAnalysisSidebar: true
      displayPreviewSidebar: true
      enableJsonLdEndpoint: ''
      enableMetaContainerEndpoint: ''
      environment: live
      generatorEnabled: true
      headersEnabled: true
      lowercaseCanonicalUrl: '1'
      maxDescriptionLength: 155
      maxTitleLength: 70
      metaCacheDuration: 'null'
      pluginName: SEOmatic
      regenerateSitemapsAutomatically: true
      renderEnabled: true
      separatorChar: '|'
      sidebarDisplayPreviewTypes:
        - google
        - twitter
        - facebook
      siteGroupsSeparate: '1'
      siteUrlOverride: ''
      sitemapsEnabled: true
      socialMediaPreviewTarget: false
      submitSitemaps: true
  site-switcher:
    edition: standard
    enabled: true
    schemaVersion: 0.0.0
  super-table:
    edition: standard
    enabled: true
    schemaVersion: 2.2.1
  template-select:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  translator:
    edition: standard
    enabled: true
    schemaVersion: 0.1.0
  twigpack:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  video-embedder:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: 'La Petite Merveille'
  schemaVersion: 3.5.13
  timeZone: Europe/London
