field: b7bb9098-e6ac-4442-909d-c493169083ad
fieldLayouts:
  35084e05-dcb1-41e9-9d0b-862043394600:
    tabs:
      -
        elements:
          -
            fieldUid: dcd0e45f-f4fe-495f-ae73-df36efb0f63c
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e1752790-6319-40ef-a732-df5a0c5a70b8
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 5d947b98-9099-494a-a2c0-4216886c7338
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  5d947b98-9099-494a-a2c0-4216886c7338:
    contentColumnType: text
    fieldGroup: null
    handle: stepButton
    instructions: ''
    name: Bouton
    searchable: true
    settings:
      selectionLabel: ' -- Sélectionner un type de lien --'
      types:
        __assoc__:
          -
            - tvXfJttK
            -
              __assoc__:
                -
                  - class
                  - flipbox\craft\link\types\Entry
                -
                  - label
                  - 'Page interne'
                -
                  - showTarget
                  - '1'
                -
                  - allowText
                  - '1'
                -
                  - requireText
                  - '1'
                -
                  - sources
                  - '*'
                -
                  - targetSiteId
                  - null
                -
                  - viewMode
                  - null
                -
                  - selectionLabel
                  - ''
                -
                  - localizeRelations
                  - ''
          -
            - bQB0ZvXd
            -
              __assoc__:
                -
                  - class
                  - flipbox\craft\link\types\Url
                -
                  - label
                  - Url
                -
                  - showTarget
                  - '1'
                -
                  - allowText
                  - '1'
                -
                  - requireText
                  - '1'
                -
                  - placeholder
                  - ''
                -
                  - useUrlAsDefaultText
                  - '1'
                -
                  - allowRelativeUrl
                  - ''
    translationKeyFormat: null
    translationMethod: none
    type: flipbox\craft\link\fields\Link
  dcd0e45f-f4fe-495f-ae73-df36efb0f63c:
    contentColumnType: text
    fieldGroup: null
    handle: stepTitle
    instructions: ''
    name: Titre
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  e1752790-6319-40ef-a732-df5a0c5a70b8:
    contentColumnType: text
    fieldGroup: null
    handle: steptext
    instructions: ''
    name: Texte
    searchable: true
    settings:
      availableTransforms: ''
      availableVolumes: ''
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Simple.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: site
    type: craft\redactor\Field
