fieldLayouts:
  dac78555-09a6-42f7-a212-adf6c3cbf327:
    tabs:
      -
        elements:
          -
            fieldUid: 67c76d67-ce8d-4f9c-81a1-9b480f2bfea0
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 395e96bd-f15a-42fe-af69-ceacfe851cc2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 8d9f05ae-9556-4338-a4ef-4d4761474c9c
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Infos globales'
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 7ad4ebb2-6984-4493-af9b-711e316d719f
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 775006d6-7318-43d0-8861-80559b0f28f5
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Flashnews
        sortOrder: 2
handle: globalInfos
name: 'Infos générales'
