enableVersioning: true
handle: accueil
name: Accueil
previewTargets:
  -
    __assoc__:
      -
        - label
        - Preview
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  3e688797-0718-4e03-a06c-6c0acf236e7b:
    enabledByDefault: true
    hasUrls: true
    template: page/accueil
    uriFormat: __home__
  84b6bb21-bdc2-41fb-b07a-7c343f7a7288:
    enabledByDefault: true
    hasUrls: true
    template: page/accueil
    uriFormat: __home__
  de5f043b-b6bd-4feb-89c2-c5e38cef6faf:
    enabledByDefault: true
    hasUrls: true
    template: page/accueil
    uriFormat: __home__
type: single
