enableVersioning: true
handle: b2b
name: B2B
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Page entrée primaire'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  3e688797-0718-4e03-a06c-6c0acf236e7b:
    enabledByDefault: true
    hasUrls: true
    template: b2b/page
    uriFormat: '{parent.uri}/{slug}'
  84b6bb21-bdc2-41fb-b07a-7c343f7a7288:
    enabledByDefault: true
    hasUrls: true
    template: b2b/page
    uriFormat: '{parent.uri}/{slug}'
  de5f043b-b6bd-4feb-89c2-c5e38cef6faf:
    enabledByDefault: true
    hasUrls: true
    template: b2b/page
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: null
  uid: cb7e9c5e-f042-4a4e-a598-cb30610a6c78
type: structure
