enableVersioning: true
handle: blog
name: Blog
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Page entrée primaire'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  3e688797-0718-4e03-a06c-6c0acf236e7b:
    enabledByDefault: true
    hasUrls: true
    template: news/index
    uriFormat: nieuws
  84b6bb21-bdc2-41fb-b07a-7c343f7a7288:
    enabledByDefault: true
    hasUrls: true
    template: news/index
    uriFormat: news
  de5f043b-b6bd-4feb-89c2-c5e38cef6faf:
    enabledByDefault: true
    hasUrls: true
    template: news/index
    uriFormat: news
type: single
