enableVersioning: true
handle: contact
name: Contact
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Page entrée primaire'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  3e688797-0718-4e03-a06c-6c0acf236e7b:
    enabledByDefault: true
    hasUrls: true
    template: page/contact
    uriFormat: contact
  84b6bb21-bdc2-41fb-b07a-7c343f7a7288:
    enabledByDefault: true
    hasUrls: true
    template: page/contact
    uriFormat: contact
  de5f043b-b6bd-4feb-89c2-c5e38cef6faf:
    enabledByDefault: true
    hasUrls: true
    template: page/contact
    uriFormat: contact
type: single
